name: Cleanup Old PR Allure Reports Workflow

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  cleanup:
    name: Cleanup old PR Allure report folders
    runs-on: ubuntu-latest

    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete reports older than 3 days
        run: |
          echo "Checking for old folders to delete..."
          now=$(date +%s)
          keep_days=3
          deleted_any=false

          for dir in run-*; do
            # Skip fixed folder
            [ "$dir" = "run-test-latest" ] && continue

            # Match folders like run-YYYY-MM-DD-*
            if [[ "$dir" =~ ^run-([0-9]{4}-[0-9]{2}-[0-9]{2})- ]]; then
              date_part="${BASH_REMATCH[1]}"
              ts=$(date -d "$date_part" +%s || echo 0)
              age_days=$(( (now - ts) / 86400 ))

              if [ "$age_days" -gt "$keep_days" ]; then
                echo "🗑️  Deleting: $dir ($age_days days old)"
                rm -rf "$dir"
                deleted_any=true
              else
                echo "✅ Keeping: $dir ($age_days days old)"
              fi
            else
              echo "⚠️  Skipping unmatched folder: $dir"
            fi
          done

          if [ "$deleted_any" = true ]; then
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git add .
            git commit -m "Cleanup old report folders (older than $keep_days days)"
            git push origin gh-pages
          else
            echo "🧹 No old folders found for cleanup."
          fi