name: PR Tests Run Workflow

on:
  pull_request:
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: read

jobs:
  run-tests:
    name: Run Tests
    uses: ./.github/workflows/run_test.yaml
    secrets: inherit
