name: PR Tests Run Workflow

on:
  pull_request:
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: read

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Set report path
        id: set-date
        run: echo "DEST=run-$(date +'%Y-%m-%d')-${{ github.run_number }}" >> "$GITHUB_OUTPUT"

      - name: Call reusable workflow
        uses: ./.github/workflows/run_test.yaml
        with:
          destination_dir: ${{ steps.set-date.outputs.DEST }}
