name: PR Tests Run Workflow

on:
  pull_request:
    branches: [ master ]

permissions:
  pull-requests: write
  contents: write
  pages: write

jobs:
  pre-commit:
    name: Pre-commit checks
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout commit
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Sync
        run: uv sync
      - name: Run pre-commit
        run: |
          echo "::add-matcher::.github/actionlint-matcher.json"
          uv run pre-commit run --all-files

  mypy:
    name: Mypy
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout commit
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Sync
        run: uv sync
      - name: Mypy
        run: |
          uv run mypy

  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Set destination directory
        id: set-destination
        run: echo "DEST=run-$(date +'%Y-%m-%d')-${{ github.run_number }}" >> "$GITHUB_ENV"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install Playwright browsers
        run: uv run python -m playwright install --with-deps

      - name: Install Allure
        run: |
          mkdir -p allure-bin
          curl -sSL -o allure.zip https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.zip
          unzip -q allure.zip -d allure-bin
          echo "$PWD/allure-bin/allure-2.27.0/bin" >> $GITHUB_PATH
          export PATH="$PWD/allure-bin/allure-2.27.0/bin:$PATH"
          allure --version

      - name: Install pytest-testmon-lite from GitHub
        run: uv pip install git+https://github.com/wkeeling/pytest-testmon-lite.git

      - name: Run changed tests with pytest-testmon-lite
        id: run_tests
        run: |
          set +e
          git fetch origin master

          echo "Collecting changed tests with pytest-testmon-lite:"
          changed=$(uv run pytest --testmon-lite --testmon-lite-diff=origin/master --collect-only -q)

          if [[ -z "$changed" ]]; then
            echo "✅ No changed tests found."
            echo "no_tests=true" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          echo "Running changed tests:"
          echo "$changed"

          uv run pytest --testmon-lite --testmon-lite-diff=origin/master -n 3 --tb=short | tee result.log
          exit_code=${PIPESTATUS[0]}

          if [[ "$exit_code" != 0 ]]; then
            echo "❌ Some tests failed."
            echo "no_tests=false" >> "$GITHUB_OUTPUT"
            exit $exit_code
          else
            echo "✅ Tests passed."
            echo "no_tests=false" >> "$GITHUB_OUTPUT"
            exit 0
          fi

      - name: Read test summary
        if: always()
        id: summary
        run: |
          if [[ "${{ steps.run_tests.outputs.no_tests }}" == "true" ]]; then
            echo "summary_text<<EOF" >> $GITHUB_OUTPUT
            echo "✅ No changed tests found in this PR." >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            echo "summary_text<<EOF" >> $GITHUB_OUTPUT
            cat reports/logs/summary.log || echo "No summary found" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          fi

      - name: Deploy to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./reports/allure-report
          publish_branch: gh-pages
          destination_dir: ${{ env.DEST }}

      - name: Comment on PR with Allure Report
        if: always()
        uses: actions/github-script@v7
        env:
          SUMMARY_TEXT: ${{ steps.summary.outputs.summary_text }}
          DEST: ${{ env.DEST }}
        with:
          script: |
            const pr = context.payload.pull_request;
            const runNumber = context.runNumber;
            const url = `https://${context.repo.owner}.github.io/${context.repo.repo}/${process.env.DEST}/index.html`;
            const summary = process.env.SUMMARY_TEXT;
            const success = "${{ steps.run_tests.outcome }}" === "success";
            const statusEmoji = success ? "✅" : "❌";
            const statusText = success ? "complete" : "failed";

            const comment = [
              `${statusEmoji} **Test run #${runNumber} ${statusText}**`,
              `📊 **Allure Report:** [View Report](${url})`,
              ``,
              `📝 **Summary:**\n\`\`\`\n${summary.trim()}\n\`\`\``
            ].join('\n');

            github.rest.issues.createComment({
              issue_number: pr.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });

      - name: Clean test artifacts to save space
        if: always()
        run: rm -rf reports/logs reports/screenshots reports/allure-results

      - name: Fail if tests failed
        if: steps.run_tests.outputs.no_tests == 'false' && steps.run_tests.outcome != 'success'
        run: exit 1


  check:
    name: Check
    needs:
      - pre-commit
      - mypy
      - run-tests
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}

  approve:
    name: Approve Pull Request
    needs: check
    if: github.event_name == 'pull_request' && always() && needs.check.result == 'success'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Approve PR
        uses: peter-evans/approve-pull-request@v5
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
