name: PR Tests Run Workflow

on:
  workflow_dispatch:
  workflow_call:

permissions:
  pull-requests: write
  contents: write

jobs:
  pre-commit:
    name: Pre-commit checks
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout commit
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Sync
        run: uv sync
      - name: Run pre-commit
        run: |
          echo "::add-matcher::.github/actionlint-matcher.json"
          uv run pre-commit run --all-files

  mypy:
      name: Mypy
      runs-on: ubuntu-latest
      timeout-minutes: 10
      steps:
        - name: Checkout commit
          uses: actions/checkout@v4
        - name: Install Python
          uses: actions/setup-python@v5
          with:
            python-version-file: .python-version
        - name: Install uv
          uses: astral-sh/setup-uv@v6
          with:
            enable-cache: true
        - name: Sync
          run: uv sync
        - name: Mypy
          run: |
            uv run mypy


  run-tests:
    name: Run Tests
    uses: ./.github/workflows/run_test.yaml
    secrets: inherit

  check:
    name: ✅ All Checks Summary
    needs:
      - pre-commit
      - mypy
      - run-tests
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
